### ISSUE TITLE
[피드백에 대한 캡슐 개선] LayoutType을 Input으로 받는 action 점검

### ISSUE THREAD

**Issue by taylous** [bixef/bixby#20]
# 상세설명

## 원인

 LayoutType을 "다음", "이전", "상세보기" 발화를 위해 "enum" 타입으로 수정한 후 발화 테스트를 하였는데 LayoutType을 input으로 받는 몇몇 action들이 동작을 안하는 현상 발생

**Comment by Karmantez** [comment]
# 상세설명

## 원인

 LayoutType을 "다음", "이전", "상세보기" 발화를 위해 "enum" 타입으로 수정한 후 발화 테스트를 하였는데 LayoutType을 input으로 받는 몇몇 action들이 동작을 안하는 현상 발생

**Comment by BeautifulBeer** [comment]
LayoutType을 Text에서 Enum 타입으로 수정함
