### ISSUE TITLE
[피드백에 대한 캡슐 개선] 레시피 검색 시 재료명 없이 발화 시 예외처리 필요

### ISSUE THREAD

**Issue by taylous** [bixef/bixby#22]
# 상세설명

 레시피 검색 시 재료명 없이 [레시피 알려줘] 발화 시, "예기치 못한 오류가 발생했습니다." 오류 발생. [어떤 레시피를 찾을까요?] 또는 추천 레시피를 보여주는 것으로 수정이 필요합니다.

**Comment by BeautifulBeer** [comment]
@Karmantez  리뷰 부탁드립니다.
