### ISSUE TITLE
[피드백에 대한 캡슐 개선] 불필요한 tagging 삭제

### ISSUE THREAD

**Issue by taylous** [bixef/bixby#25]
# 상세설명

##  대상

1. SearchKeyword
2. LowerBoundKeyword,
3. UpperBoundKeyword
4. GuideKeyword

## 설명

 Bixby Training 진행 시 동사 태깅을 지양하고 있습니다. 이는 공통적으로 사용 빈도수가 높고, 어느 한 캡슐의 특성으로 보기 어려운 것을 태깅할 시 빅스비가 어느 캡슐에 꽂혀야 할지 혼돈이 발생하기 때문에 삭제해야 합니다.

**Comment by BeautifulBeer** [comment]
GuideKeyword 또한 제거 완료
